### ISSUE TITLE
How execute SQL

### ISSUE THREAD

**Issue by alu** [ivanceras/rustorm#11]
@ivanceras 
Hi.

I want to execute SQL that does not need return value like below.

```sql
UPDATE user set name = ? where id = ?
```

I looked for match to the objective, but i can't found it.
What should I use?

**Comment by ivanceras** [comment]
HI @alu, I just added update example for mysql [here](https://github.com/ivanceras/rustorm/blob/mysql-support/examples/update_usage_mysql.rs) . The api is clunky at the moment, will find some time to clean it up.

**Comment by alu** [comment]
@ivanceras Thank you very much for your kindness :D.
