### ISSUE TITLE
return Result instead of using unwrap

### ISSUE THREAD

**Issue by Fiedzia** [ivanceras/rustorm#2]
I don't think that problem with getting data from db is good reason for panicking.

**Comment by ivanceras** [comment]
The README is a bit outdated, As you can see in the source code https://github.com/ivanceras/rustorm/blob/master/src/query.rs#L958 , here it returns Option, which is comparable to Result. Maybe result is better than Option in this situation.

**Comment by Fiedzia** [comment]
What I mean really is that db api should always return Result everywhere, and never panic. In my opinion panicking is really something only application developer is allowed to do, not the library. Also result can carry much more details than panic.

**Comment by ivanceras** [comment]
https://github.com/ivanceras/rustorm/commit/68072184fb43c3d72c3b05eeede6c12984b8ea20

**Comment by mtorromeo** [comment]
I see there are still a lot of unwrap() all over the place. Is this issue really considered closed?
I get a panic if the db server is unreachable while I would like to display a useful message to the user...
