### ISSUE TITLE
Option with custom types

### ISSUE THREAD

**Issue by alu** [ivanceras/rustorm#21]
@ivanceras Hi! Thank you for merging my PR :D. But i got new problem :(.

We have defined several custom type such as `Id(i64)`.

It can be used as query parameter if we defined `impl rustorm::ToValue for Id`.

```rust
impl rustorm::ToValue for Id {
    fn to_value(&self) -> rustorm::Value {
        rustorm::Value::Bigint(self.0)
    }
}

#[derive(Debug, FromDao)]
struct R {}

let _: Vec<R> = em
    .execute_sql_with_return("SELECT id FROM table id = ?", &[&Id(99)])
    .unwrap();
```

It can be used as result type if we defined `impl From<&rustorm::Value> for Id`.

```rust
impl From<&rustorm::Value> for Id {
    fn from(v: &rustorm::Value) -> Id {
        match v {
            rustorm::Value::Bigint(v) => Id(*v),
            _ => panic!("unable to convert"),
        }
    }
}

#[derive(Debug, FromDao)]
struct R {
    e: Id,
}

let _: Vec<R> = em
    .execute_sql_with_return("SELECT id FROM table", &[])
    .unwrap();
```

But we can't be used if it wrapted by `Option` because `From` and `ToValue` are external trait, and `Option` is external type.

The newtype pattern such as `Id(i64)` is general in Rust so I think it ’s worth making it available.
I think need new trait such as `FromValue` for instead of `From`.
But it's will makes broken changes.

What do you think the idea?

**Comment by ivanceras** [comment]
If you owned one of the type (in the case Id), you should be able to convert with From and ToValue.
In this case `impl From<Value> for Id` is OK, but `From<Value> for Option<Id>` is not possible. (I thought this was possible at first).
Yes, we may need to have the FromValue trait. Let me see what you'll come up with. I'll be willing to merge them.

**Comment by alu** [comment]
@ivanceras 
I posted new PR.
Please check it out ;P
