### ISSUE TITLE
use r2d2-mysql backend

### ISSUE THREAD

**Issue by daogangtang** [ivanceras/rustorm#24]
now r2d2 support mysql pool, I will post a pr later.

**Comment by ivanceras** [comment]
Hi,
Thank you for your interest in this project.
Please take note that there is an ongoing development in the develop branch, which has a drastic change and addition to the API.

Example usage can be found here.

[rustorm example](https://github.com/ivanceras/rustorm/blob/develop/examples/complex_query.rs)

[codegenta example](https://github.com/ivanceras/codegenta/blob/develop/examples/complex_query.rs)

This may take a long time before merging it back to master for a release.

**Comment by daogangtang** [comment]
ok, I do my work on a new branch, then merge your new refactored work, :)

**Comment by ivanceras** [comment]
Rustorm is using an early version of `mysql` crate. Needs to update the crate first then use r2d2 mysql connection pooling follows.
