### ISSUE TITLE
Always creates new pool in call em()

### ISSUE THREAD

**Issue by alu** [ivanceras/rustorm#26]
@ivanceras Hi!

`Pool::em()` calls `ensure()`, so it calls `init_pool` always finally for now.
I thinks it's not necessary and happens problems sometime maybe.

**Comment by ivanceras** [comment]
Hi @alu , this looks like an oversight on my part. I haven't trace up when exactly a lot of the `ensure()` calls was introduced. Feel free to experiment by removing/minimizing the call of `ensure()`. I will get back on this when I have some other time.
