### ISSUE TITLE
latest status?

### ISSUE THREAD

**Issue by daogangtang** [ivanceras/rustorm#29]
When I look in to diesel for using, I find that it is not as good as people expect. In my option, rustorm is better in usage (at lease now.)

So, I want to ask the status of rustorm now, and the plan of it in the future? 

thx.

**Comment by ivanceras** [comment]
Diesel is best use for apps tailored for its specific database, while rustorm is suited to be used for building apps that relies on meta table information, such as PgAdmin. I am still actively maintaining the project, but my main focus right now is building database admin apps like https://github.com/ivanceras/curtain

**Comment by daogangtang** [comment]
nice client. And I will use rustorm. :)

**Comment by ivanceras** [comment]
I've tried to use diesel for a domain specific projects, but it lacks handling complex queries like aggregations and reporting queries. So, I'm going to continue improving rustorm to handle complex queries.
