### ISSUE TITLE
Mysql requires mutable connection

### ISSUE THREAD

**Issue by ivanceras** [ivanceras/rustorm#4]
https://github.com/blackbeam/rust-mysql-simple.
Mysql driver requires a mutable connection, In order to support Mysql, the database trait needs to be mutable when it is borrowed. This requires changes in the API's which was mostly immutable borrows of Database trait.

**Comment by blackbeam** [comment]
I think you can wrap `MyPool` instead of `MyConn` and use `MyPool::prepare` and `MyPool::prep_exec`.

**Comment by ivanceras** [comment]
Thanks, will look into this. I'll revert the API back to use immutable &Database borrow again.

**Comment by ivanceras** [comment]
Committed a fix on this https://github.com/ivanceras/rustorm/commit/141d49b96315082bf72fe766cc7db65bee96b9a2
