### ISSUE TITLE
Problem to adopt it.

### ISSUE THREAD

**Issue by daogangtang** [ivanceras/rustorm#5]
Hi,  rustorm_dao, and rustorm_codegen should update to latest on crates.io, so we can do development using rustorm.

**Comment by daogangtang** [comment]
u haven't divide rustorm_dao, and rustorm_codegen to separate repos, and don't use workspace to organize them, so don't know how to import them.

**Comment by ivanceras** [comment]
The rustorm crate is a part of the workspace in diwata, cargo doesn't
support nested workspaces.

**Comment by ivanceras** [comment]
You can use the `replace` feature in cargo.

**Comment by daogangtang** [comment]
Done, as follow:
```
[dependencies.rustorm]
git = "https://github.com/ivanceras/rustorm"
features = ["with-postgres"]

[dependencies.rustorm_dao]
git = "https://github.com/ivanceras/rustorm"

[dependencies.rustorm_codegen]
git = "https://github.com/ivanceras/rustorm"

```
