### ISSUE TITLE
Strings from database surrounded with \' on either side

### ISSUE THREAD

**Issue by freiguy1** [ivanceras/rustorm#7]
I'm using rustorm with mysql.  I've got a table of states (filled with info on the fifty United States) with a column of abbreviations.  I select all abbreviations this way:

```rust
let abbreviations = Query::select().from_table("state").column("abbreviation").retrieve(db.as_ref()).unwrap()
```

Then map them to a list of strings this way:

```rust
let abbreviations: Vec<String> = abbreviations.dao.iter().map(|dao| dao.get::<String>("abbreviation")).collect()
```

When i `println` abbreviations, I get:

```
["\'AK\'", "\'AL\'", "\'AS\'", "\'AZ\'", "\'AR\'", "\'CA\'", "\'CO\'", "\'CT\'", "\'DE\'", "\'FL\'", "\'GA\'", "\'HI\'", "\'ID\'", "\'IL\'", "\'IN\'", "\'IA\'", "\'KS\'", "\'KY\'", "\'LA\'", "\'ME\'", "\'MD\'", "\'MA\'", "\'MI\'", "\'MN\'", "\'MS\'", "\'MO\'", "\'MT\'", "\'NE\'", "\'NV\'", "\'NH\'", "\'NJ\'", "\'NM\'", "\'NY\'", "\'NC\'", "\'ND\'", "\'OH\'", "\'OK\'", "\'OR\'", "\'PA\'", "\'RI\'", "\'SC\'", "\'SD\'", "\'TN\'", "\'TX\'", "\'UT\'", "\'VT\'", "\'VA\'", "\'WA\'", "\'WV\'", "\'WI\'", "\'WY\'"]
```

When I believe I should be getting just 

```
["AK", "AL" ...]
```

Am I doing something incorrectly or is the library?

**Comment by ivanceras** [comment]
I'll take a look on this. Thanks for filing an issue.

**Comment by ivanceras** [comment]
As you can see here in these line https://github.com/ivanceras/rustorm/blob/79e52f95eaff287cde5dac0b21eefc7cc253ae56/src/platform/mysql.rs#L48

All data types has been converted to string for mysql, this was a quick hack for providing a quick input, output results for mysql, but forgot to stabilize it into a usable api.
