### ISSUE TITLE
Can’t compile due to OpenSSL

### ISSUE THREAD

**Issue by batisteo** [ivanceras/rustorm#9]
I can’t compile Diwata because Rustorm is using an old version of the crate `openssl`:
https://github.com/sfackler/rust-openssl/issues/987

Would it be possible to bump up the version of `openssl` in the depencecies?

**Comment by ivanceras** [comment]
@batisteo can you post the error log?
Also make sure `openssl` or `libssl` is installed in your workspace enviroment.
ssl package in ubuntu is `libssl-dev`

**Comment by batisteo** [comment]
I’ve got OpenSLL version `1.1.1c` and I got the same error as in the linked issue, and was solved in another project by bumping the crate version.
Are you using a mac which has an old version?

**Comment by ivanceras** [comment]
@batisteo No, I don't have a mac. I've read it from somewhere there's a bit of a problem/conflicts when installing or updating ssl library in mac. I'll try to setup travis-ci for mac.

**Comment by ivanceras** [comment]
I updated my rust toolchain and started seeing this now. I'll get this fix soon.

**Comment by ivanceras** [comment]
[Fixed](https://github.com/ivanceras/rustorm/commit/1cc7d3e8bde6175b374a52e5a0b98b92f9a280d5)

**Comment by batisteo** [comment]
Awesome, thanks!
